### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by gen4sp** [devery/deveryjs#4]
```
Error: only one instance of babel-polyfill is allowed
    at Object.eval (webpack-internal:///./node_modules/babel-polyfill/lib/index.js:10:9)
    at eval (webpack-internal:///./node_modules/babel-polyfill/lib/index.js:29:30)
    at Object../node_modules/babel-polyfill/lib/index.js (/Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:306:1)
    at __webpack_require__ (/Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:21:30)
    at eval (webpack-internal:///./index.js:1:202)
    at Object../index.js (/Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:282:1)
    at __webpack_require__ (/Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:21:30)
    at Object.0 (/Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:5617:18)
    at __webpack_require__ (/Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:21:30)
    at /Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:85:18
    at Object.<anonymous> (/Users/gen4/Gits/node-sku-server-vova/node_modules/@devery/devery/dist/index.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gen4/Gits/node-sku-server-vova/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
```
I dont use babel-polyfill in my code.
Any ideas?

**Comment by andrewrd** [comment]
Did you install via the yarn lockfile? It's likely dependency related.

**Comment by gen4sp** [comment]
yes, with yarn

**Comment by gen4sp** [comment]
maybe the solution is to use `import 'idempotent-babel-polyfill';` instead of `babel-polyfill` in the library?

**Comment by gen4sp** [comment]
solved with using backback.js for compiling. 
there was another issue, but I've made a pull request for that.
